spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb://mongo-rs-db1:27017,mongo-rs-db1:27018,mongo-rs-db1:27019/customerDB?replicaSet=rs0&retryWrites=true


server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka